In [2]:
from aflow_wrapper import *

In [7]:
%%time
o_sr_ti = aflow_fetch(["Sr", "Ti", "O"])

Searching for O,Sr,Ti ...
ERROR: http://aflowlib.duke.edu/search/API/?enthalpy_atom,compound,composition,species('O,Sr,Ti'),natoms,geometry,natoms,positions_fractional,positions_cartesian,species('O,Sr,Ti'),nspecies(3),paging(1,20)

DB Fail!null


TypeError: '<' not supported between instances of 'int' and 'NoneType'

In [6]:
o_sr_ti

auid  \
0    aflow:a398a1911df830b6   
1    aflow:dd6b539aa43315cf   
2    aflow:cf8261dc98053c05   
3    aflow:24084cffd0913299   
4    aflow:84426b1f2bca94bf   
..                      ...   
130  aflow:1081ae07cd17668e   
131  aflow:be8c85026b2903bf   
132  aflow:3df5cb2068b28e46   
133  aflow:a92f502219060c36   
134  aflow:7b285634f7870a03   

                                                  aurl   compound composition  \
0    aflowlib.duke.edu:AFLOWDATA/LIB3_RAW/OSr_svTi_...   O3Sr1Ti1   [3, 1, 1]   
1    aflowlib.duke.edu:AFLOWDATA/ICSD_WEB/MCLC/O13S...  O13Sr2Ti6  [13, 2, 6]   
2    aflowlib.duke.edu:AFLOWDATA/LIB3_RAW/OSr_svTi_...   O4Sr2Ti1   [4, 2, 1]   
3    aflowlib.duke.edu:AFLOWDATA/ICSD_WEB/ORC/O3.8S...  O19Sr5Ti7  [19, 5, 7]   
4    aflowlib.duke.edu:AFLOWDATA/ICSD_WEB/ORCI/O3Sr...   O6Sr2Ti2   [6, 2, 2]   
..                                                 ...        ...         ...   
130  aflowlib.duke.edu:AFLOWDATA/ICSD_WEB/CUB/O3Sr1...   O3Sr1Ti1   [3, 1, 1]   
131  aflowlib.duke.edu:AFLOWDATA/ICSD_WEB/BCT/O3Sr1...   O6Sr2Ti2   [6, 2, 2]   
132  aflowlib.duke.edu:AFLOWDATA/ICSD_WEB/CUB/O3Sr1...   O3Sr1Ti1   [3, 1, 1]   
133  aflowlib.duke.edu:AFLOWDATA/ICSD_WEB/BCT/O3Sr1...   O6Sr2Ti2   [6, 2, 2]   
134  aflowlib.duke.edu:AFLOWDATA/LIB3_RAW/OSr_svTi_...   O3Sr1Ti1   [3, 1, 1]   

         species natoms                                           geometry  \
0    [O, Sr, Ti]      5   [3.944917, 3.944917, 3.944917, 90.0, 90.0, 90.0]   
1    [O, Sr, Ti]     21  [7.997203, 7.997203, 9.276024, 81.31587, 81.31...   
2    [O, Sr, Ti]      7  [6.922171, 6.922171, 6.922171, 147.0365, 147.0...   
3    [O, Sr, Ti]     31   [3.857699, 5.653635, 32.53007, 90.0, 90.0, 90.0]   
4    [O, Sr, Ti]     10  [5.618459, 5.618459, 5.618459, 120.2416, 120.2...   
..           ...    ...                                                ...   
130  [O, Sr, Ti]      5  [3.4562624, 3.4562624, 3.4562624, 90.0, 90.0, ...   
131  [O, Sr, Ti]     10  [4.8845388, 4.8845388, 4.8845388, 120.16275, 1...   
132  [O, Sr, Ti]      5  [3.4165353, 3.4165353, 3.4165353, 90.0, 90.0, ...   
133  [O, Sr, Ti]     10  [4.8283946, 4.8283946, 4.8283946, 120.16275, 1...   
134  [O, Sr, Ti]      5  [4.4055512, 4.4055512, 4.4055512, 90.0, 90.0, ...   

                                  positions_fractional  \
0    [[0.5, 0.5, 0.0], [0.0, 0.5, 0.5], [0.5, 0.0, ...   
1    [[-0.0, -0.0, -0.0], [0.22969052, 0.22969052, ...   
2    [[-0.0, 0.5, 0.5], [0.5, 0.0, 0.5], [0.8417448...   
3    [[0.0, -0.0, 0.27020073], [0.0, 0.0, 0.7297992...   
4    [[0.74844344, 0.5, 0.24844344], [0.24844344, -...   
..                                                 ...   
130  [[0.5, 0.5, 0.0], [0.0, 0.5, 0.5], [0.5, 0.0, ...   
131  [[0.24999965, 0.24999965, 0.0], [0.75000035, 0...   
132  [[0.5, 0.5, 0.0], [0.0, 0.5, 0.5], [0.5, 0.0, ...   
133  [[0.24999965, 0.24999965, 0.0], [0.75000035, 0...   
134  [[-0.0, 0.5, 0.5], [0.5, -0.0, 0.5], [0.5, 0.5...   

                                   positions_cartesian  enthalpy_atom  
0    [[1.97246, 1.97246, -0.0], [0.0, 1.97246, 1.97...       -8.04063  
1    [[0.0, -0.0, 0.0], [0.0, 4.66767, 6.91916], [0...       -7.74586  
2    [[1.96389, 0.0, 0.0], [0.0, 1.96389, 0.0], [-0...       -7.50088  
3    [[0.0, -0.0, 8.78965], [0.0, 0.0, 23.74042], [...       -7.47655  
4    [[-0.0, 1.39077, 3.98732], [0.0, 1.39077, 0.0]...       -7.47642  
..                                                 ...            ...  
130  [[1.72813, 1.72813, 0.0], [0.0, 1.72813, 1.728...       -5.90040  
131  [[0.0, 0.0, 1.73118], [0.0, 0.0, 5.19356], [1....       -5.88242  
132  [[1.70827, 1.70827, 0.0], [0.0, 1.70827, 1.708...       -5.58013  
133  [[0.0, 0.0, 1.71128], [0.0, 0.0, 5.13386], [1....       -5.55959  
134  [[0.0, 2.20278, 2.20278], [2.20278, 0.0, 2.202...       -4.63824  

[135 rows x 10 columns]

In [4]:
o_sr_ti.to_pickle("OSrTi.pkl")

In [3]:
o_sr_ti = pd.read_pickle("OSrTi.pkl")

In [4]:
o_sr_ti.compound.unique()

array(['O3Sr1Ti1', 'O13Sr2Ti6', 'O4Sr2Ti1', 'O19Sr5Ti7', 'O6Sr2Ti2',
       'O20Sr4Ti8', 'O10Sr4Ti3', 'O7Sr3Ti2'], dtype=object)

In [20]:
r = o_sr_ti.loc[2]
r.compound

'O4Sr2Ti1'

In [21]:
r.geometry

array([  6.922171,   6.922171,   6.922171, 147.0365  , 147.0365  ,
        47.30972 ])

In [113]:
A = calc_basis(r.geometry)
A

array([[ 6.922171  ,  4.69347411, -5.80782162],
       [ 0.        ,  5.0880008 , -2.54399999],
       [ 0.        ,  0.        ,  2.77735907]])

In [23]:
r.positions_fractional

array([[-0.        ,  0.5       ,  0.5       ],
       [ 0.5       ,  0.        ,  0.5       ],
       [ 0.84174488,  0.84174488, -0.        ],
       [ 0.15825512,  0.15825512,  0.        ],
       [ 0.64534685,  0.64534685, -0.        ],
       [ 0.35465315,  0.35465315, -0.        ],
       [-0.        ,  0.        , -0.        ]])

In [90]:
def elements_coords(entry, augment=True):
    elements = []
    for e, n in zip(entry.species, entry.composition):
        elements = elements + [e]*n
        
        
    pfs_list = list(entry.positions_fractional)
    
    if augment:
        for element, coords in zip(elements, pfs_list):
            for i, c in enumerate(coords):
                if c == 0:
                    new_coords = coords.copy()
                    new_coords[i] = 1.

                    already_in = False
                    for other_p in pfs_list:
                        if all(other_p == new_coords):
                            already_in = True
                            break

                    if not already_in:
                        pfs_list.append(new_coords)
                        elements.append(element)
    
    pfs = np.array(pfs_list)
    
    A = calc_basis(entry.geometry)
    cartesian_coords = calc_cartesian_positions(A, pfs)
    
    return elements, cartesian_coords
                

In [94]:
elements_coords(r)

(['O',
  'O',
  'O',
  'O',
  'Sr',
  'Sr',
  'Ti',
  'O',
  'O',
  'O',
  'O',
  'Sr',
  'Sr',
  'Ti',
  'Ti',
  'Ti',
  'Ti',
  'Ti',
  'Ti',
  'Ti'],
 array([[-0.55717376,  1.2720004 ,  1.38867954],
        [ 0.55717469, -1.272     ,  1.38867954],
        [ 9.7774098 ,  4.28279862,  0.        ],
        [ 1.83823531,  0.80520218,  0.        ],
        [ 7.49611998,  3.28352529,  0.        ],
        [ 4.11952513,  1.80447551,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 6.36499724,  1.2720004 ,  1.38867954],
        [ 5.2506488 ,  3.8160008 ,  1.38867954],
        [ 3.96958818,  1.73879863,  2.77735907],
        [-3.96958631, -1.73879781,  2.77735907],
        [ 1.68829836,  0.7395253 ,  2.77735907],
        [-1.68829649, -0.73952448,  2.77735907],
        [ 6.922171  ,  0.        ,  0.        ],
        [ 4.69347411,  5.0880008 ,  0.        ],
        [-5.80782162, -2.54399999,  2.77735907],
        [11.61564511,  5.0880008 ,  0.        ],
        [ 1.11

In [24]:
poss = calc_cartesian_positions(A, r.positions_fractional)
poss

array([[-0.55717376,  1.2720004 ,  1.38867954],
       [ 0.55717469, -1.272     ,  1.38867954],
       [ 9.7774098 ,  4.28279862,  0.        ],
       [ 1.83823531,  0.80520218,  0.        ],
       [ 7.49611998,  3.28352529,  0.        ],
       [ 4.11952513,  1.80447551,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [25]:
r.positions_cartesian

array([[ 1.96389,  0.     ,  0.     ],
       [ 0.     ,  1.96389,  0.     ],
       [-0.     , -0.     , 10.67427],
       [ 0.     ,  0.     ,  2.00685],
       [-0.     , -0.     ,  8.18373],
       [-0.     , -0.     ,  4.4974 ],
       [ 0.     , -0.     ,  0.     ]])

In [26]:
r.auid

'aflow:cf8261dc98053c05'

In [99]:
plot_3D_crystal(r)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [30]:
import ase
%matplotlib widget
import nglview

In [114]:
elements, coords = elements_coords(r, augment=False)
mol = ase.Atoms(symbols=elements, positions=coords, pbc=True, cell=A)

In [115]:
mol.positions

array([[-0.55717376,  1.2720004 ,  1.38867954],
       [ 0.55717469, -1.272     ,  1.38867954],
       [ 9.7774098 ,  4.28279862,  0.        ],
       [ 1.83823531,  0.80520218,  0.        ],
       [ 7.49611998,  3.28352529,  0.        ],
       [ 4.11952513,  1.80447551,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [116]:
mol.cell

Cell([[6.922171, 4.69347410867248, -5.80782161999487], [0.0, 5.08800080035981, -2.54399999091037], [0.0, 0.0, 2.77735907469834]])

In [117]:
view = nglview.show_ase(mol)
view.background="black"
display(view)

NGLWidget(background='black')

In [92]:
elements, coords = elements_coords(r)

In [93]:
fig = plt.figure()
ax = Axes3D(fig)
ax.scatter(coords[:,0], coords[:,1], coords[:,2], alpha=1, s=25)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [ ]:
from voxel import *

In [ ]:
for compound in o_sr_ti.compound.unique():
    print(compound)
    matches = o_sr_ti[o_sr_ti.compound == compound]
    
    r = matches.iloc[0]
    A = calc_basis(r.geometry)
    mus = calc_cartesian_positions(A, r.positions_fractional)
    sigma = 0.5
    plot_3D_crystal(r)
    
    B, mi, sg = reciprocal_lattice_gaussian(A, mus, sigma, g0=-8, g1=8)
    plot_3D_reciprocal_lattice(B, mi, sg)

    
    